### ISSUE TITLE
Question about maintainance

### ISSUE THREAD

**Issue by petre2dor** [Akemona/strapi#12]
Hi @imaksp,

Thanks for making this fork.
I am interested in supporting this effort and keeping this project going.

Can we have a discussion about this?

Cheers,
Petre

**Comment by imaksp** [comment]
Hi, thanks for the offer, currently we are focusing only on latest LTS node & latest mongo support (SQL users can use strapi v4+), in coming months I will work on adding Node 20 support & will update mongoose to latest & will also try to update koa server. 
& as new features are not added there won't be much work, but still you can send PR if you find any major issue in this.

**Comment by petre2dor** [comment]
That sounds good, thanks!
