### ISSUE TITLE
Parse mongo connection string throws Invalid URL

### ISSUE THREAD

**Issue by petre2dor** [Akemona/strapi#14]
A mongodb connection string with [multiple hosts](https://www.mongodb.com/docs/manual/reference/connection-string/) is not a valid URL in [NodeJS](https://nodejs.org/docs/latest/api/url.html#urlprotocol), for example `mongodb://foo:123,bar:432/?a=b` cannot be parsed as `URL`, so strapi fails to start and throws `Invalid URL`.

**Comment by imaksp** [comment]
Hi, this is fixed in [3.15.2.](https://github.com/Akemona/strapi/releases/tag/v3.15.2)
